In [1]:
import numpy as np
import matplotlib.image as mpimg
import cv2

In [2]:
img = mpimg.imread('binary_combo_example.jpg')
print(img.shape)

(720, 1280)


In [3]:
img1 = cv2.imread('binary_combo_example.jpg')
print(img1.shape)

(720, 1280, 3)


In [59]:
b=np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [101]:
print(b[-1:,-1:])

[[43]]


In [47]:
c=np.array(b[:,1:2])
print(c.shape)


(5, 1)


In [52]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])
print(c.shape)
for row in c:
    print(row)

(2, 2, 3)
[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [58]:
d =np.array([[ 9.,  5.,  6.,  3.,  6.,  8.,  0.,  7.,  9.,  7.,  2.,  7.],
       [ 1.,  4.,  9.,  2.,  2.,  1.,  0.,  6.,  2.,  2.,  4.,  0.]])
e = np.hsplit(d,4)
print(e)

[array([[ 9.,  5.,  6.],
       [ 1.,  4.,  9.]]), array([[ 3.,  6.,  8.],
       [ 2.,  2.,  1.]]), array([[ 0.,  7.,  9.],
       [ 0.,  6.,  2.]]), array([[ 7.,  2.,  7.],
       [ 2.,  4.,  0.]])]


In [112]:
f=np.arange(0,27)
f=f.reshape(3,3,3)
print(f[-2:,:2,:])

[[[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
